


 //-------------UDEMY EXERSICES-----------------





/*// TASK HOW TO PRINT STRINGS VERTICALLY "HELLO"

var str ="hello";
var count=0;
while (count<str.length){
	console.log(str[count]);
	count++;
}*/ //TASK HOW TO PRINT STRINGS VERTICALLY "HELLO"


/*// SECRET GAME PROGRAM

var secretNum=8, num;
 for (var i=0; i<3; i++){
	 num=prompt("Guess a secret number");
	 if(secretNum==num){
		console.log("Win")
		 
	 }else if (num<secretNum){
			 console.log("Too low");
		 }
		 else if(num>secretNum){
			 console.log(" Too high");
				 
			 }
 }console.log("you lost");*/ //SECRET GAME PROGRAM


			 